spring:
    profiles: standalone
    datasource:
        url: jdbc:mysql://localhost:3306/dev_db
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
server:
    port: 9001   